### ISSUE TITLE
Issue publishing

### ISSUE THREAD

**Issue by XingZiLong** [wenyan-lang/wyg-registry#18]
I saw my package merged 10 hours ago but I still cannot see my package updated. What’s the problem?
Thanks!

**Comment by antfu** [comment]
Is there anything I can help with? If you mean the `typeof` package, I can see that in the readme of this repo and the online IDE as well.

**Comment by XingZiLong** [comment]
Sorry for my mistake :)


| |
xzl2628655535
|
|
邮箱：xzl2628655535@163.com
|

Signature is customized by Netease Mail Master

On 03/16/2020 15:33, Anthony Fu wrote:

Is there anything I can help with? If you mean the typeof package, I can see that in the readme of this repo and the online IDE as well.
