### ISSUE TITLE
wyg.wy-lang.org

### ISSUE THREAD

**Issue by antfu** [wenyan-lang/wyg-registry#4]
In recent commits, I have added an url redirect system that allows user import package even without wyg to resolve the names (I was so excited it works). Here is an example:

[https://wyg-registry.netlify.com/pkg/子曰](https://wyg-registry.netlify.com/pkg/%E5%AD%90%E6%9B%B0)

https://wyg-registry.netlify.com/pkg/kelou

I think it's better to be `wyg.wy-lang.org` than `wyg-registry.netlify.com`. @LingDong- What do you think?

**Comment by LingDong-** [comment]
![image](https://user-images.githubusercontent.com/7929704/74277376-6d1c1480-4ce5-11ea-9c8a-8260ed48e645.png)

Sounds like a great idea! but unfortunately it appears that I cannot add it because wy-lang.org itself is using the same domain.

I think we should stop netlify from taking over the nameservers, and use the original domain registrar (name.com in our case) instead, where subdomain records are straightforward to add.

Found a doc for that: https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/#configure-a-subdomain

If you too think that is a good idea, I can start working on it :)

**Comment by antfu** [comment]
Sure. I think the CNAME should definitely work. If you would like to do so, can you help to bind `ide` and `snippets` as well? Thanks.

An alternative way is that you may need to transfer the main site to the wenyan-lang team and make the [domain manage by the team](https://app.netlify.com/teams/wenyan-lang/dns). In this way, I think subdomains can be set for multiple sites with a few clicks.

**Comment by LingDong-** [comment]
Well, I transferred wenyan homepage to wenyan-lang team.
I followed your "domain manage by the team" link
Doesn't allow me to add the domain for the old reason.
Removed the domain on wenyan homepage and tried again
Still doesn't work
Tried to add wy-lang.org back to the wenyan homepage
That breaks too!
WTF!
Now all our homepage shows is

```
Not found
```

**Comment by antfu** [comment]
What? I will have a look

**Comment by antfu** [comment]
@LingDong- Maybe it's bound to the default team of your account? Can you check it out?

**Comment by LingDong-** [comment]
![image](https://user-images.githubusercontent.com/7929704/74291304-7798d700-4d02-11ea-8dc1-3fa016ce2a60.png)

**Comment by LingDong-** [comment]
I added a URL redirect (A record) on registrar name.com to wenyan.netlify.com as a temporary measure, but that either doesn't work, or doesn't work yet.
Please let me know if there's anything I can change on name.com while you investigate, thanks!

**Comment by antfu** [comment]
![image](https://user-images.githubusercontent.com/11247099/74291384-af8a3380-4d6f-11ea-9cc5-30b4a103c58c.png)

Can you check out here?

**Comment by LingDong-** [comment]
![image](https://user-images.githubusercontent.com/7929704/74291466-eb3ae400-4d02-11ea-9f54-43fb3d041d23.png)
When I do "Add or register domain", it doesn't let me, because it thinks "Another account is already using this domain"

**Comment by LingDong-** [comment]
Our homepage is back, phew!

Sorry for the panic. I didn't realize I need to delete the domain from my netlify account. I thought it was enough to disassociate it with wenyan-lang.netlify.com.

Thanks for spotting the problem!

**Comment by LingDong-** [comment]
http://wyg.wy-lang.org/
http://snippets.wy-lang.org/
http://ide.wy-lang.org/

All good :D 🚀

**Comment by antfu** [comment]
Great! Thanks! 🚀

**Comment by antfu** [comment]
I have updated the links in numbers of repos to the new domain! Will write a script to migrate and redirect the IDE later (passing localStorage etc.)
